### ISSUE TITLE
关于 L 题的数据正确性和合法性

### ISSUE THREAD

**Issue by Larry0716** [THUSAAC/THUPC2023-Pre#1]
首先，感谢出题组能公开题面、数据、数据校验器等 THUPC 2023 初赛的比赛细节，但是似乎 L 题的细节方面出现了一些问题，希望有同学能够给予一些帮助。

具体问题如下：

本人对第 25、27、31、35、40 测试点的答案合法性表示质疑

本人对第 2、3、4、5、7、29、34、38 测试点的答案正确性或 `conf.yaml` 中所描述的 `std.cpp` 的正确性表示质疑。

本人对测试点数目表示质疑，对 `data` 目录下的 `val.cpp` 的有效性或全体 `.in` 数据的合法性表示质疑

在这里先提前感谢大家的回答了。

**Comment by Steaunk** [comment]
感谢同学的指正，已更新 5401581。比赛时数据是正确的，第一次上传时的数据有误。
